# Generated by Django 3.1.7 on 2021-03-11 12:57

import cpffield.cpffield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', cpffield.cpffield.CPFField(max_length=14, verbose_name='CPF')),
                ('date_birth', models.DateField()),
            ],
        ),
    ]
