# Generated by Django 3.1.7 on 2021-03-17 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 18, 25, 5, 204500)),
        ),
        migrations.AddField(
            model_name='person',
            name='deleted_at',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 18, 25, 5, 204533)),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateField(default=datetime.datetime(2021, 3, 17, 18, 25, 5, 204520)),
        ),
    ]
