# Generated by Django 3.1.7 on 2021-03-21 02:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210320_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='stacks',
        ),
        migrations.CreateModel(
            name='StackPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(default=datetime.datetime(2021, 3, 21, 2, 10, 31, 288269))),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='core.person')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='core.stack')),
            ],
            options={
                'unique_together': {('stack', 'person')},
            },
        ),
    ]
