# Generated by Django 3.1.7 on 2021-03-17 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210317_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='stack',
        ),
        migrations.AddField(
            model_name='stack',
            name='Person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='core.person'),
        ),
    ]
