# Generated by Django 3.1.7 on 2021-03-21 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210321_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackperson',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 19, 20, 37, 882820)),
        ),
    ]
