# Generated by Django 3.1.7 on 2021-03-22 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210321_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='stacks',
            field=models.ManyToManyField(related_name='person_stacks', through='core.StackPerson', to='core.Stack'),
        ),
        migrations.AlterField(
            model_name='stackperson',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 0, 59, 24, 23887)),
        ),
    ]
