# Generated by Django 3.1.7 on 2021-03-22 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210322_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='stacks',
        ),
        migrations.AlterField(
            model_name='stackperson',
            name='datetime',
            field=models.DateField(default=datetime.datetime(2021, 3, 22, 1, 39, 55, 626401)),
        ),
    ]
